# Generated by Django 6.0.7 on 2026-07-18 15:37

import uuid

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_alter_user_managers_user_job_title_alter_user_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="facebook_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="user",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.RemoveField(
            model_name="user",
            name="x_url",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region="NG"
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("website", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
    ]
